name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        arch:
          - arm64
          - x64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        # node-pre-gyp is broken on newer versions of Node on Windows
        # https://github.com/mapbox/node-pre-gyp/issues/715
        node-version: '20.11.1'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        yarn install

    - name: Build
      run: |
        yarn build:ci --target_arch=${{ matrix.arch }} --arch=${{ matrix.arch }}

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          yarn test --target_arch=${{ matrix.arch }}
